services:


 minecraft-ai-bot:

  build:

   context: ..


  container_name:
   minecraft-ai-bot


  restart:
   always


  env_file:

   - ../.env


  volumes:

   - ../data:/app/data


  ports:

   - "3000:3000"